import type { Metadata } from "next";
import { hedvig } from "./ui/fonts";
import "./globals.css";
import Nav from "./ui/Nav";
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import Footer from "./ui/Footer";

config.autoAddCss = false


export const metadata: Metadata = {
  title: "Roofers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${hedvig.className} antialiased relative`}
      >
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
